# Generated by Django 6.1 on 2026-08-24 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام اتاق')),
                ('room_type', models.CharField(choices=[('private', 'خصوصی'), ('group', 'گروهی')], default='private', max_length=10, verbose_name='نوع اتاق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('participants', models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='شرکت\u200cکنندگان')),
            ],
            options={
                'verbose_name': 'اتاق چت',
                'verbose_name_plural': 'اتاق\u200cهای چت',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('message_type', models.CharField(choices=[('text', 'متن'), ('image', 'تصویر'), ('file', 'فایل')], default='text', max_length=10, verbose_name='نوع پیام')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='اتاق')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
                'ordering': ['timestamp'],
            },
        ),
    ]
